//! Every UI mark the clients draw: [Lucide](https://lucide.dev) v0.462.0 (ISC — see
//! THIRD-PARTY-NOTICES.txt), in the two forms the shells need.
//!
//! **The path** is the master SVG's shapes folded into one 24×24 path string. The Skia
//! console parses it with Skia and the GTK shell with `gsk::Path`, both stroking at
//! Lucide's native width 2 with round caps and joins — so one mark cannot come out
//! differently on the two shells.
//!
//! **The glyph** is the same icon's codepoint in Lucide's own icon font. The WinUI shell
//! draws that instead: windows-reactor has no vector element, and a font glyph is the one
//! form WinUI sizes and tints for itself, like the `SymbolIcon` it replaced.
//!
//! GENERATED by `scripts/gen-lucide-assets.sh` from `assets/lucide/` — do not edit.

/// Lucide `activity`.
pub const ACTIVITY: &str = "M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2";
/// Lucide `arrow-left`.
pub const ARROW_LEFT: &str = "M12 19l-7-7 7-7M19 12H5";
/// Lucide `arrow-right`.
pub const ARROW_RIGHT: &str = "M5 12h14M12 5l7 7-7 7";
/// Lucide `arrow-up-down`.
pub const ARROW_UP_DOWN: &str = "M21 16l-4 4-4-4M17 20V4M3 8l4-4 4 4M7 4v16";
/// Lucide `bug`.
pub const BUG: &str = "M8 2l1.88 1.88M14.12 3.88 16 2M9 7.13v-1a3.003 3.003 0 1 1 6 0v1M12 20c-3.3 0-6-2.7-6-6v-3a4 4 0 0 1 4-4h4a4 4 0 0 1 4 4v3c0 3.3-2.7 6-6 6M12 20v-9M6.53 9C4.6 8.8 3 7.1 3 5M6 13H2M3 21c0-2.1 1.7-3.9 3.8-4M20.97 5c0 2.1-1.6 3.8-3.5 4M22 13h-4M17.2 17c2.1.1 3.8 1.9 3.8 4";
/// Lucide `chart-column`.
pub const CHART_COLUMN: &str = "M3 3v16a2 2 0 0 0 2 2h16M18 17V9M13 17V5M8 17v-3";
/// Lucide `check`.
pub const CHECK: &str = "M20 6 9 17l-5-5";
/// Lucide `chevron-down`.
pub const CHEVRON_DOWN: &str = "M6 9l6 6 6-6";
/// Lucide `chevron-left`.
pub const CHEVRON_LEFT: &str = "M15 18l-6-6 6-6";
/// Lucide `chevron-right`.
pub const CHEVRON_RIGHT: &str = "M9 18l6-6-6-6";
/// Lucide `chevron-up`.
pub const CHEVRON_UP: &str = "M18 15l-6-6-6 6";
/// Lucide `circle-help`.
pub const CIRCLE_HELP: &str =
    "M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3M12 17h.01";
/// Lucide `clock`.
pub const CLOCK: &str = "M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0M12 6L12 12L16 14";
/// Lucide `copy`.
pub const COPY: &str = "M10 8h10a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2zM4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2";
/// Lucide `corner-down-left`.
pub const CORNER_DOWN_LEFT: &str = "M9 10L4 15L9 20M20 4v7a4 4 0 0 1-4 4H4";
/// Lucide `cpu`.
pub const CPU: &str = "M6 4h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2zM10 9h4a1 1 0 0 1 1 1v4a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1zM15 2v2M15 20v2M2 15h2M2 9h2M20 15h2M20 9h2M9 2v2M9 20v2";
/// Lucide `ellipsis`.
pub const ELLIPSIS: &str = "M11 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0M18 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0M4 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0";
/// Lucide `eye`.
pub const EYE: &str = "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0";
/// Lucide `film`.
pub const FILM: &str = "M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2zM7 3v18M3 7.5h4M3 12h18M3 16.5h4M17 3v18M17 7.5h4M17 16.5h4";
/// Lucide `gamepad-2`.
pub const GAMEPAD_2: &str = "M6 11L10 11M8 9L8 13M15 12L15.01 12M18 10L18.01 10M17.32 5H6.68a4 4 0 0 0-3.978 3.59c-.006.052-.01.101-.017.152C2.604 9.416 2 14.456 2 16a3 3 0 0 0 3 3c1 0 1.5-.5 2-1l1.414-1.414A2 2 0 0 1 9.828 16h4.344a2 2 0 0 1 1.414.586L17 18c.5.5 1 1 2 1a3 3 0 0 0 3-3c0-1.545-.604-6.584-.685-7.258-.007-.05-.011-.1-.017-.151A4 4 0 0 0 17.32 5z";
/// Lucide `gauge`.
pub const GAUGE: &str = "M12 14l4-4M3.34 19a10 10 0 1 1 17.32 0";
/// Lucide `grip-vertical`.
pub const GRIP_VERTICAL: &str = "M8 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0M8 5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0M8 19a1 1 0 1 0 2 0a1 1 0 1 0 -2 0M14 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0M14 5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0M14 19a1 1 0 1 0 2 0a1 1 0 1 0 -2 0";
/// Lucide `heart`.
pub const HEART: &str = "M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z";
/// Lucide `house`.
pub const HOUSE: &str = "M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8M3 10a2 2 0 0 1 .709-1.528l7-5.999a2 2 0 0 1 2.582 0l7 5.999A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z";
/// Lucide `info`.
pub const INFO: &str = "M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0M12 16v-4M12 8h.01";
/// Lucide `keyboard`.
pub const KEYBOARD: &str = "M10 8h.01M12 12h.01M14 8h.01M16 12h.01M18 8h.01M6 8h.01M7 16h10M8 12h.01M4 4h16a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2z";
/// Lucide `link`.
pub const LINK: &str = "M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71";
/// Lucide `lock`.
pub const LOCK: &str = "M5 11h14a2 2 0 0 1 2 2v7a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-7a2 2 0 0 1 2 -2zM7 11V7a5 5 0 0 1 10 0v4";
/// Lucide `log-out`.
pub const LOG_OUT: &str = "M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4M16 17L21 12L16 7M21 12L9 12";
/// Lucide `maximize`.
pub const MAXIMIZE: &str = "M8 3H5a2 2 0 0 0-2 2v3M21 8V5a2 2 0 0 0-2-2h-3M3 16v3a2 2 0 0 0 2 2h3M16 21h3a2 2 0 0 0 2-2v-3";
/// Lucide `menu`.
pub const MENU: &str = "M4 12L20 12M4 6L20 6M4 18L20 18";
/// Lucide `mic-off`.
pub const MIC_OFF: &str = "M2 2L22 22M18.89 13.23A7.12 7.12 0 0 0 19 12v-2M5 10v2a7 7 0 0 0 12 5M15 9.34V5a3 3 0 0 0-5.68-1.33M9 9v3a3 3 0 0 0 5.12 2.12M12 19L12 22";
/// Lucide `mic`.
pub const MIC: &str =
    "M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3ZM19 10v2a7 7 0 0 1-14 0v-2M12 19L12 22";
/// Lucide `monitor`.
pub const MONITOR: &str = "M4 3h16a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2zM8 21L16 21M12 17L12 21";
/// Lucide `moon`.
pub const MOON: &str = "M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z";
/// Lucide `mouse`.
pub const MOUSE: &str =
    "M12 2h0a7 7 0 0 1 7 7v6a7 7 0 0 1 -7 7h0a7 7 0 0 1 -7 -7v-6a7 7 0 0 1 7 -7zM12 6v4";
/// Lucide `palette`.
pub const PALETTE: &str = "M13 6.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0M17 10.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0M8 7.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0M6 12.5a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z";
/// Lucide `panel-right`.
pub const PANEL_RIGHT: &str =
    "M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2zM15 3v18";
/// Lucide `pencil`.
pub const PENCIL: &str = "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497zM15 5l4 4";
/// Lucide `pin`.
pub const PIN: &str = "M12 17v5M9 10.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H8a2 2 0 0 0 0 4 1 1 0 0 1 1 1z";
/// Lucide `play`.
pub const PLAY: &str = "M6 3L20 12L6 21L6 3z";
/// Lucide `plus`.
pub const PLUS: &str = "M5 12h14M12 5v14";
/// Lucide `pointer`.
pub const POINTER: &str = "M22 14a8 8 0 0 1-8 8M18 11v-1a2 2 0 0 0-2-2a2 2 0 0 0-2 2M14 10V9a2 2 0 0 0-2-2a2 2 0 0 0-2 2v1M10 9.5V4a2 2 0 0 0-2-2a2 2 0 0 0-2 2v10M18 11a2 2 0 1 1 4 0v3a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15";
/// Lucide `power`.
pub const POWER: &str = "M12 2v10M18.4 6.6a9 9 0 1 1-12.77.04";
/// Lucide `refresh-cw`.
pub const REFRESH_CW: &str = "M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8M21 3v5h-5M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16M8 16H3v5";
/// Lucide `rotate-cw`.
pub const ROTATE_CW: &str = "M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8M21 3v5h-5";
/// Lucide `save`.
pub const SAVE: &str = "M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2zM17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7M7 3v4a1 1 0 0 0 1 1h7";
/// Lucide `scroll-text`.
pub const SCROLL_TEXT: &str = "M15 12h-5M15 8h-5M19 17V5a2 2 0 0 0-2-2H4M8 21h12a2 2 0 0 0 2-2v-1a1 1 0 0 0-1-1H11a1 1 0 0 0-1 1v1a2 2 0 1 1-4 0V5a2 2 0 1 0-4 0v2a1 1 0 0 0 1 1h3";
/// Lucide `search`.
pub const SEARCH: &str = "M3 11a8 8 0 1 0 16 0a8 8 0 1 0 -16 0M21 21l-4.3-4.3";
/// Lucide `send`.
pub const SEND: &str = "M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11zM21.854 2.147l-10.94 10.939";
/// Lucide `settings`.
pub const SETTINGS: &str = "M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2zM9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0";
/// Lucide `sliders-horizontal`.
pub const SLIDERS_HORIZONTAL: &str = "M21 4L14 4M10 4L3 4M21 12L12 12M8 12L3 12M21 20L16 20M12 20L3 20M14 2L14 6M8 10L8 14M16 18L16 22";
/// Lucide `square`.
pub const SQUARE: &str =
    "M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z";
/// Lucide `star`.
pub const STAR: &str = "M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z";
/// Lucide `sun`.
pub const SUN: &str = "M8 12a4 4 0 1 0 8 0a4 4 0 1 0 -8 0M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41";
/// Lucide `trash-2`.
pub const TRASH_2: &str = "M3 6h18M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2M10 11L10 17M14 11L14 17";
/// Lucide `tv`.
pub const TV: &str =
    "M4 7h16a2 2 0 0 1 2 2v11a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2v-11a2 2 0 0 1 2 -2zM17 2L12 7L7 2";
/// Lucide `undo-2`.
pub const UNDO_2: &str = "M9 14 4 9l5-5M4 9h10.5a5.5 5.5 0 0 1 5.5 5.5a5.5 5.5 0 0 1-5.5 5.5H11";
/// Lucide `volume-2`.
pub const VOLUME_2: &str = "M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298zM16 9a5 5 0 0 1 0 6M19.364 18.364a9 9 0 0 0 0-12.728";
/// Lucide `wrench`.
pub const WRENCH: &str = "M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z";
/// Lucide `x`.
pub const X: &str = "M18 6 6 18M6 6l12 12";

/// Every icon: its Lucide name, its path data, and its glyph in the icon font.
pub const ALL: &[(&str, &str, char)] = &[
    ("activity", ACTIVITY, '\u{e038}'),
    ("arrow-left", ARROW_LEFT, '\u{e04c}'),
    ("arrow-right", ARROW_RIGHT, '\u{e04d}'),
    ("arrow-up-down", ARROW_UP_DOWN, '\u{e381}'),
    ("bug", BUG, '\u{e20c}'),
    ("chart-column", CHART_COLUMN, '\u{e2a3}'),
    ("check", CHECK, '\u{e070}'),
    ("chevron-down", CHEVRON_DOWN, '\u{e071}'),
    ("chevron-left", CHEVRON_LEFT, '\u{e072}'),
    ("chevron-right", CHEVRON_RIGHT, '\u{e073}'),
    ("chevron-up", CHEVRON_UP, '\u{e074}'),
    ("circle-help", CIRCLE_HELP, '\u{e082}'),
    ("clock", CLOCK, '\u{e08b}'),
    ("copy", COPY, '\u{e0a2}'),
    ("corner-down-left", CORNER_DOWN_LEFT, '\u{e0a5}'),
    ("cpu", CPU, '\u{e0ad}'),
    ("ellipsis", ELLIPSIS, '\u{e0ba}'),
    ("eye", EYE, '\u{e0be}'),
    ("film", FILM, '\u{e0d4}'),
    ("gamepad-2", GAMEPAD_2, '\u{e0e2}'),
    ("gauge", GAUGE, '\u{e1bf}'),
    ("grip-vertical", GRIP_VERTICAL, '\u{e0ee}'),
    ("heart", HEART, '\u{e0f5}'),
    ("house", HOUSE, '\u{e0f8}'),
    ("info", INFO, '\u{e0fe}'),
    ("keyboard", KEYBOARD, '\u{e284}'),
    ("link", LINK, '\u{e108}'),
    ("lock", LOCK, '\u{e10f}'),
    ("log-out", LOG_OUT, '\u{e112}'),
    ("maximize", MAXIMIZE, '\u{e116}'),
    ("menu", MENU, '\u{e119}'),
    ("mic-off", MIC_OFF, '\u{e11d}'),
    ("mic", MIC, '\u{e11c}'),
    ("monitor", MONITOR, '\u{e121}'),
    ("moon", MOON, '\u{e122}'),
    ("mouse", MOUSE, '\u{e28e}'),
    ("palette", PALETTE, '\u{e1dd}'),
    ("panel-right", PANEL_RIGHT, '\u{e436}'),
    ("pencil", PENCIL, '\u{e1f9}'),
    ("pin", PIN, '\u{e259}'),
    ("play", PLAY, '\u{e140}'),
    ("plus", PLUS, '\u{e141}'),
    ("pointer", POINTER, '\u{e1e8}'),
    ("power", POWER, '\u{e144}'),
    ("refresh-cw", REFRESH_CW, '\u{e149}'),
    ("rotate-cw", ROTATE_CW, '\u{e14d}'),
    ("save", SAVE, '\u{e151}'),
    ("scroll-text", SCROLL_TEXT, '\u{e464}'),
    ("search", SEARCH, '\u{e155}'),
    ("send", SEND, '\u{e156}'),
    ("settings", SETTINGS, '\u{e158}'),
    ("sliders-horizontal", SLIDERS_HORIZONTAL, '\u{e29a}'),
    ("square", SQUARE, '\u{e16b}'),
    ("star", STAR, '\u{e17a}'),
    ("sun", SUN, '\u{e17c}'),
    ("trash-2", TRASH_2, '\u{e18e}'),
    ("tv", TV, '\u{e195}'),
    ("undo-2", UNDO_2, '\u{e2a1}'),
    ("volume-2", VOLUME_2, '\u{e1ab}'),
    ("wrench", WRENCH, '\u{e1b1}'),
    ("x", X, '\u{e1b2}'),
];

/// One icon's path data by its Lucide name; `None` for a name this build does not ship.
pub fn path(name: &str) -> Option<&'static str> {
    ALL.iter().find(|(n, _, _)| *n == name).map(|(_, d, _)| *d)
}

/// One icon's codepoint in Lucide's icon font — what a shell that draws the FONT needs.
/// `None` for a name this build does not ship.
pub fn glyph(name: &str) -> Option<char> {
    ALL.iter().find(|(n, _, _)| *n == name).map(|(_, _, g)| *g)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every icon is reachable by its own name in both forms, the names are unique, and a
    /// name this build does not ship resolves to nothing rather than to the wrong mark.
    #[test]
    fn every_icon_is_reachable_by_name() {
        for (name, data, g) in ALL {
            assert_eq!(path(name), Some(*data), "{name}");
            assert_eq!(glyph(name), Some(*g), "{name}");
            assert!(!data.is_empty(), "{name} has no path");
            // Lucide's font puts every icon in the Private Use Area.
            assert!(
                ('\u{e000}'..='\u{f8ff}').contains(g),
                "{name}: {g:?} is not a private-use codepoint"
            );
        }
        let mut names: Vec<_> = ALL.iter().map(|(n, _, _)| *n).collect();
        names.sort_unstable();
        names.dedup();
        assert_eq!(names.len(), ALL.len(), "a name is used twice");
        let mut glyphs: Vec<_> = ALL.iter().map(|(_, _, g)| *g).collect();
        glyphs.sort_unstable();
        glyphs.dedup();
        assert_eq!(glyphs.len(), ALL.len(), "two icons share a glyph");
        assert_eq!(path("no-such-icon"), None);
        assert_eq!(glyph("no-such-icon"), None);
    }
}
