//! The presenter shaders as committed SPIR-V blobs (`shaders/`, regenerated by
//! `shaders/build.sh` — no build-time toolchain).
//!
//! They live here, not with the Vulkan presenter that used to own them, because the
//! PyroWave lane needs the planar pair on Android too and that client depends on this
//! crate rather than on `pf-presenter`. Bytes only — no ash, no feature gate — so the
//! module costs nothing on a target that never builds a pipeline.
//!
//! `include_bytes!` alignment is unspecified; every consumer copies through
//! `ash::util::read_spv` (or its own aligned copy) before handing the words to Vulkan.

/// Bufferless fullscreen triangle. Every CSC/overlay pipeline's vertex stage.
pub const FULLSCREEN_VERT: &[u8] = include_bytes!("../shaders/fullscreen.vert.spv");
/// NV12 (Y + interleaved CbCr) → RGBA, push-constant CSC rows.
pub const NV12_CSC_FRAG: &[u8] = include_bytes!("../shaders/nv12_csc.frag.spv");
/// Three-plane YCbCr → RGBA — the PyroWave and software rungs' variant.
pub const PLANAR_CSC_FRAG: &[u8] = include_bytes!("../shaders/planar_csc.frag.spv");
/// The console overlay's premultiplied-alpha blit.
pub const OVERLAY_FRAG: &[u8] = include_bytes!("../shaders/overlay.frag.spv");
/// The same blit onto an HDR10 swapchain: sRGB UI re-encoded as PQ at 203-nit white.
pub const OVERLAY_PQ_FRAG: &[u8] = include_bytes!("../shaders/overlay_pq.frag.spv");
/// One axis of the video scale: nearest, Catmull-Rom or widened Lanczos-3.
pub const SCALE_FRAG: &[u8] = include_bytes!("../shaders/scale.frag.spv");
