#!/usr/bin/env python3
"""Fold each Lucide master's shapes into one SVG path string and write the shared Rust table.

Usage: gen-lucide-icons.py <svg-dir> <out.rs>   (both given by scripts/gen-lucide-assets.sh)

Each icon carries BOTH forms it is drawn in: the folded path (Skia on the console, gsk in the
GTK shell) and the icon font's codepoint, read from <svg-dir>/font/info.json (the WinUI shell,
which has no vector element and draws the glyph instead).

The output is `crates/client/pf-client-core/src/lucide.rs` — ONE table for every Rust client, so the
Skia console and the GTK shell cannot draw a mark differently. Generated outright rather than
printed for pasting: 32 paths of up to 1 kB each is a transcription error waiting to happen,
and a mangled character is a silently wrong icon rather than a build failure.
"""

import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

NS = "{http://www.w3.org/2000/svg}"


def num(s):
    v = float(s)
    return int(v) if v == int(v) else v


def absolutize_leading_move(d):
    """A leading relative `m` is absolute only at the START of a path; concatenated after
    another element it would move relative to that element's end. Rewrite it as an absolute
    `M` — and since implicit pairs after `m` are RELATIVE linetos, spell the `l` out."""
    m = re.match(r"^m\s*(-?[\d.]+)[\s,]+(-?[\d.]+)\s*(.*)$", d, re.S)
    if not m:
        return d
    x, y, rest = m.group(1), m.group(2), m.group(3)
    if rest and not rest[0].isalpha():
        rest = "l" + rest
    return f"M{x} {y}{rest}"


def shape_to_path(el):
    tag = el.tag.removeprefix(NS)
    a = el.attrib
    if tag == "path":
        return absolutize_leading_move(a["d"])
    if tag == "line":
        x1, y1, x2, y2 = (num(a[k]) for k in ("x1", "y1", "x2", "y2"))
        return f"M{x1} {y1}L{x2} {y2}"
    if tag == "circle":
        cx, cy, r = num(a["cx"]), num(a["cy"]), num(a["r"])
        return (
            f"M{num(cx - r)} {cy}"
            f"a{r} {r} 0 1 0 {num(2 * r)} 0"
            f"a{r} {r} 0 1 0 {num(-2 * r)} 0"
        )
    if tag == "rect":
        x, y = num(a.get("x", "0")), num(a.get("y", "0"))
        w, h = num(a["width"]), num(a["height"])
        rx = num(a.get("rx", "0"))
        ry = num(a.get("ry", str(rx))) or rx
        if not rx:
            return f"M{x} {y}h{w}v{h}h{num(-w)}z"
        return (
            f"M{num(x + rx)} {y}h{num(w - 2 * rx)}"
            f"a{rx} {ry} 0 0 1 {rx} {ry}v{num(h - 2 * ry)}"
            f"a{rx} {ry} 0 0 1 {num(-rx)} {ry}h{num(-(w - 2 * rx))}"
            f"a{rx} {ry} 0 0 1 {num(-rx)} {num(-ry)}v{num(-(h - 2 * ry))}"
            f"a{rx} {ry} 0 0 1 {rx} {num(-ry)}z"
        )
    if tag in ("polyline", "polygon"):
        pts = re.findall(r"[-\d.]+", a["points"])
        pairs = [f"{num(pts[i])} {num(pts[i + 1])}" for i in range(0, len(pts), 2)]
        d = "M" + "L".join(pairs)
        return d + ("z" if tag == "polygon" else "")
    raise SystemExit(f"unhandled element <{tag}>")


def convert(svg_file):
    root = ET.parse(svg_file).getroot()
    assert root.attrib.get("viewBox") == "0 0 24 24", svg_file
    assert root.attrib.get("stroke-width") == "2", svg_file
    return "".join(shape_to_path(el) for el in root)


def main():
    d, out = Path(sys.argv[1]), Path(sys.argv[2])
    # The icon font's name -> private-use codepoint map, shipped with the masters.
    info = json.loads((d / "font" / "info.json").read_text())
    icons = []
    for f in sorted(d.glob("*.svg")):
        data = convert(f)
        assert '"' not in data, f
        # `encodedCode` is a CSS escape — one backslash then the hex codepoint, e.g. \e04c.
        code = info[f.stem]["encodedCode"]
        assert re.fullmatch(r"\\[0-9a-f]{4}", code), (f.stem, code)
        icons.append((f.stem, f.stem.replace("-", "_").upper(), data, code[1:]))

    lines = [
        "//! Every UI mark the clients draw: [Lucide](https://lucide.dev) v0.462.0 (ISC — see",
        "//! THIRD-PARTY-NOTICES.txt), in the two forms the shells need.",
        "//!",
        "//! **The path** is the master SVG's shapes folded into one 24×24 path string. The Skia",
        "//! console parses it with Skia and the GTK shell with `gsk::Path`, both stroking at",
        "//! Lucide's native width 2 with round caps and joins — so one mark cannot come out",
        "//! differently on the two shells.",
        "//!",
        "//! **The glyph** is the same icon's codepoint in Lucide's own icon font. The WinUI shell",
        "//! draws that instead: windows-reactor has no vector element, and a font glyph is the one",
        "//! form WinUI sizes and tints for itself, like the `SymbolIcon` it replaced.",
        "//!",
        "//! GENERATED by `scripts/gen-lucide-assets.sh` from `assets/lucide/` — do not edit.",
        "",
    ]
    for name, ident, data, code in icons:
        lines.append(f"/// Lucide `{name}`.")
        lines.append(f'pub const {ident}: &str = "{data}";')
    lines += [
        "",
        "/// Every icon: its Lucide name, its path data, and its glyph in the icon font.",
        "pub const ALL: &[(&str, &str, char)] = &[",
    ]
    lines += [
        f"    (\"{name}\", {ident}, '\\u{{{code}}}')," for name, ident, _, code in icons
    ]
    lines += [
        "];",
        "",
        "/// One icon's path data by its Lucide name; `None` for a name this build does not ship.",
        "pub fn path(name: &str) -> Option<&'static str> {",
        "    ALL.iter().find(|(n, _, _)| *n == name).map(|(_, d, _)| *d)",
        "}",
        "",
        "/// One icon's codepoint in Lucide's icon font — what a shell that draws the FONT needs.",
        "/// `None` for a name this build does not ship.",
        "pub fn glyph(name: &str) -> Option<char> {",
        "    ALL.iter().find(|(n, _, _)| *n == name).map(|(_, _, g)| *g)",
        "}",
        "",
        "#[cfg(test)]",
        "mod tests {",
        "    use super::*;",
        "",
        "    /// Every icon is reachable by its own name in both forms, the names are unique, and a",
        "    /// name this build does not ship resolves to nothing rather than to the wrong mark.",
        "    #[test]",
        "    fn every_icon_is_reachable_by_name() {",
        "        for (name, data, g) in ALL {",
        "            assert_eq!(path(name), Some(*data), \"{name}\");",
        "            assert_eq!(glyph(name), Some(*g), \"{name}\");",
        "            assert!(!data.is_empty(), \"{name} has no path\");",
        "            // Lucide's font puts every icon in the Private Use Area.",
        "            assert!(",
        "                ('\\u{e000}'..='\\u{f8ff}').contains(g),",
        "                \"{name}: {g:?} is not a private-use codepoint\"",
        "            );",
        "        }",
        "        let mut names: Vec<_> = ALL.iter().map(|(n, _, _)| *n).collect();",
        "        names.sort_unstable();",
        "        names.dedup();",
        "        assert_eq!(names.len(), ALL.len(), \"a name is used twice\");",
        "        let mut glyphs: Vec<_> = ALL.iter().map(|(_, _, g)| *g).collect();",
        "        glyphs.sort_unstable();",
        "        glyphs.dedup();",
        "        assert_eq!(glyphs.len(), ALL.len(), \"two icons share a glyph\");",
        "        assert_eq!(path(\"no-such-icon\"), None);",
        "        assert_eq!(glyph(\"no-such-icon\"), None);",
        "    }",
        "}",
        "",
    ]
    out.write_text("\n".join(lines))
    print(f"{out}: {len(icons)} icons (path + glyph)")


if __name__ == "__main__":
    main()
