#!/usr/bin/env python3
"""Emit the controller drawings from the assets/pads masters.

One master per controller, front-on, in millimetres. Paint order is document order, and each
element's class names its part (assets/pads/README.md). Two tables come out of it:

    crates/pf-console-ui/src/pad_art.rs           console input test, Skia
    web/src/sections/Diagnostics/Controllers/padArt.ts        web console Controllers page, inline SVG

Usage: python3 scripts/gen_pad_art.py     (from anywhere; paths are repo-relative)
"""

from __future__ import annotations

import pathlib
import re
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET

from svg_marks import ROOT, comment, write

MASTERS = ROOT / "assets" / "pads"
RUST = "crates/pf-console-ui/src/pad_art.rs"
TS = "web/src/sections/Diagnostics/Controllers/padArt.ts"
NS = "{http://www.w3.org/2000/svg}"

# A kind with no master of its own draws as the controller it carries.
ALIASES = {"steamcontroller2puck": "steamcontroller2"}

BANNER = (
    "GENERATED by scripts/gen_pad_art.py from the assets/pads masters.\n"
    "Do not edit by hand — edit a master and re-run the script."
)

CLASSES = {"body", "panel", "line", "button", "trigger", "stick", "pad", "glyph", "mark", "label"}


def num(v: float) -> str:
    s = f"{v:.3f}".rstrip("0").rstrip(".")
    return "0" if s == "-0" else s


def flt(v: float) -> str:
    """A Rust `f32` literal."""
    s = num(v)
    return s if "." in s else f"{s}.0"


def f(el: ET.Element, attr: str, default: float | None = None) -> float:
    v = el.get(attr)
    if v is None:
        if default is None:
            raise ValueError(f"<{el.tag[len(NS):]}> needs {attr}")
        return default
    return float(v)


def shape_d(el: ET.Element) -> str:
    """Path data for any basic shape."""
    tag = el.tag[len(NS):]
    if tag == "path":
        return " ".join(el.get("d").split())
    if tag in ("circle", "ellipse"):
        cx, cy = f(el, "cx", 0), f(el, "cy", 0)
        rx = f(el, "r") if tag == "circle" else f(el, "rx")
        ry = rx if tag == "circle" else f(el, "ry")
        return (
            f"M{num(cx - rx)} {num(cy)}a{num(rx)} {num(ry)} 0 1 0 {num(2 * rx)} 0"
            f"a{num(rx)} {num(ry)} 0 1 0 {num(-2 * rx)} 0Z"
        )
    if tag == "rect":
        x, y, w, h = f(el, "x", 0), f(el, "y", 0), f(el, "width"), f(el, "height")
        rx = min(f(el, "rx", f(el, "ry", 0)), w / 2)
        ry = min(f(el, "ry", rx), h / 2)
        if rx == 0:
            return f"M{num(x)} {num(y)}h{num(w)}v{num(h)}h{num(-w)}Z"

        def arc(dx: float, dy: float) -> str:
            return f"a{num(rx)} {num(ry)} 0 0 1 {num(dx)} {num(dy)}"

        return (
            f"M{num(x + rx)} {num(y)}h{num(w - 2 * rx)}{arc(rx, ry)}v{num(h - 2 * ry)}"
            f"{arc(-rx, ry)}h{num(-(w - 2 * rx))}{arc(-rx, -ry)}v{num(-(h - 2 * ry))}{arc(rx, -ry)}Z"
        )
    if tag == "line":
        x1, y1, x2, y2 = (num(f(el, a, 0)) for a in ("x1", "y1", "x2", "y2"))
        return f"M{x1} {y1}L{x2} {y2}"
    if tag in ("polyline", "polygon"):
        pts = [float(v) for v in re.split(r"[\s,]+", el.get("points").strip())]
        xy = [f"{num(pts[i])} {num(pts[i + 1])}" for i in range(0, len(pts), 2)]
        return "M" + "L".join(xy) + ("Z" if tag == "polygon" else "")
    raise ValueError(f"<{tag}> is not a shape")


def parts(el: ET.Element, out: list[dict], token: str) -> None:
    for child in el:
        tag = child.tag[len(NS):] if child.tag.startswith(NS) else child.tag
        if tag in ("title", "desc", "style", "defs", "metadata"):
            continue
        if child.get("transform"):
            sys.exit(f"{token}: transform on <{tag}> is not supported; bake it")
        if tag == "g":
            parts(child, out, token)
            continue
        cls = child.get("class")
        if cls not in CLASSES:
            sys.exit(f"{token}: <{tag}> needs a class from {sorted(CLASSES)}, has {cls!r}")
        p: dict = {"k": cls}
        if cls in ("trigger", "stick", "pad"):
            p["id"] = child.get("id") or sys.exit(f"{token}: a {cls} needs an id")
        if cls == "button":
            # No id: a control the wire does not carry. It draws, and never lights.
            p["id"] = child.get("id", "")
        if cls in ("glyph", "mark", "label"):
            p["on"] = child.get("data-on", "")
        if cls in ("stick", "pad"):
            if tag != "circle":
                sys.exit(f"{token}: a {cls} is a <circle>")
            p.update(cx=f(child, "cx"), cy=f(child, "cy"), r=f(child, "r"))
        elif cls == "label":
            p.update(
                x=f(child, "x"),
                y=f(child, "y"),
                size=f(child, "font-size", 4),
                text=(child.text or "").strip(),
            )
        else:
            p["d"] = shape_d(child)
            if cls == "glyph":
                p["w"] = f(child, "stroke-width", 1)
        out.append(p)


def load(path: pathlib.Path) -> dict:
    token = path.stem
    root = ET.parse(path).getroot()
    x, y, w, h = (float(v) for v in root.get("viewBox").split())
    if x != 0 or y != 0:
        sys.exit(f"{token}: viewBox must start at 0 0")
    title = root.find(f"{NS}title")
    name = title.text.strip() if title is not None and title.text else token
    out: list[dict] = []
    parts(root, out, token)
    if not any(p["k"] == "body" for p in out):
        sys.exit(f"{token}: no body")
    return {"token": token, "name": name, "w": w, "h": h, "parts": out}


def quote(s: str) -> str:
    if any(c in s for c in '"\\\n'):
        sys.exit(f"string {s!r} carries a quote, backslash or newline")
    return f'"{s}"'


def ident(token: str) -> str:
    return token.upper().replace("8", "EIGHT")


# --- console (Rust) ---------------------------------------------------------------------------


def rust_part(p: dict) -> str:
    k = p["k"]
    if k in ("body", "panel", "line"):
        return f"Part::{k.capitalize()}({quote(p['d'])})"
    if k in ("button", "trigger"):
        return f"Part::{k.capitalize()}({quote(p['id'])}, {quote(p['d'])})"
    if k in ("stick", "pad"):
        return (
            f"Part::Stick {{ id: {quote(p['id'])}, cx: {flt(p['cx'])}, cy: {flt(p['cy'])}, "
            f"r: {flt(p['r'])}, pad: {'true' if k == 'pad' else 'false'} }}"
        )
    if k == "glyph":
        return f"Part::Glyph {{ on: {quote(p['on'])}, d: {quote(p['d'])}, w: {flt(p['w'])} }}"
    if k == "mark":
        return f"Part::Mark {{ on: {quote(p['on'])}, d: {quote(p['d'])} }}"
    return (
        f"Part::Label {{ on: {quote(p['on'])}, x: {flt(p['x'])}, y: {flt(p['y'])}, "
        f"size: {flt(p['size'])}, text: {quote(p['text'])} }}"
    )


def rust_static(a: dict) -> str:
    rows = "\n".join(f"        {rust_part(p)}," for p in a["parts"])
    return (
        f"static {ident(a['token'])}: PadArt = PadArt {{\n"
        f"    w: {flt(a['w'])},\n    h: {flt(a['h'])},\n"
        f"    parts: &[\n{rows}\n    ],\n}};"
    )


def rust(arts: list[dict], entries: list[tuple[str, str]]) -> str:
    arms = "\n".join(f"        {quote(k)} => &{ident(v)}," for k, v in entries)
    statics = "\n\n".join(rust_static(a) for a in arts)
    return f"""{comment(BANNER, "//!")}
//!
//! Each controller front-on in its master's millimetre box, parts in paint order. Ids are the
//! console's button names (`A`, `LB`, `Up`, `L4`, `Touchpad`, `Misc`…) and the stick names.

/// One controller drawing.
pub(crate) struct PadArt {{
    pub w: f32,
    pub h: f32,
    pub parts: &'static [Part],
}}

/// A drawing part. Path data is SVG syntax in the master's units.
pub(crate) enum Part {{
    /// The shell: filled, with a rim.
    Body(&'static str),
    /// A recess or a second material, darker than the shell.
    Panel(&'static str),
    /// A seam or an outline, stroked.
    Line(&'static str),
    /// A control that lights while its id is held. An empty id never lights.
    Button(&'static str, &'static str),
    /// A control that fills with its id's axis.
    Trigger(&'static str, &'static str),
    /// A stick well, or with `pad` a trackpad, moved by its id's axes and lit by its click.
    Stick {{
        id: &'static str,
        cx: f32,
        cy: f32,
        r: f32,
        pad: bool,
    }},
    /// Stroked ink on the control `on`.
    Glyph {{
        on: &'static str,
        d: &'static str,
        w: f32,
    }},
    /// Filled ink on the control `on`.
    Mark {{ on: &'static str, d: &'static str }},
    /// Text centred on `(x, y)`, on the control `on`.
    Label {{
        on: &'static str,
        x: f32,
        y: f32,
        size: f32,
        text: &'static str,
    }},
}}

/// The drawing for a `GamepadPref` name; `None` for a name with no master.
pub(crate) fn art(kind: &str) -> Option<&'static PadArt> {{
    Some(match kind {{
{arms}
        _ => return None,
    }})
}}

{statics}
"""


# --- web console (TS) -------------------------------------------------------------------------


def ts_part(p: dict) -> str:
    rows = []
    for key, v in p.items():
        if key == "k" and v == "pad":
            v = "stick"
        rows.append(f"\t\t\t\t{key}: {quote(v) if isinstance(v, str) else num(v)},")
    if p["k"] in ("stick", "pad"):
        rows.append(f"\t\t\t\tpad: {'true' if p['k'] == 'pad' else 'false'},")
    return "\t\t\t{\n" + "\n".join(rows) + "\n\t\t\t},"


def ts_key(k: str) -> str:
    return k if k.isidentifier() else quote(k)


def ts_entry(a: dict) -> str:
    rows = "\n".join(ts_part(p) for p in a["parts"])
    return (
        f"\t{ts_key(a['token'])}: {{\n"
        f"\t\tname: {quote(a['name'])},\n\t\tw: {num(a['w'])},\n\t\th: {num(a['h'])},\n"
        f"\t\tparts: [\n{rows}\n\t\t],\n\t}},"
    )


def ts(arts: list[dict]) -> str:
    entries = "\n".join(ts_entry(a) for a in arts)
    aliases = "\n".join(
        f"\t{ts_key(k)}: ART{'.' + v if v.isidentifier() else f'[{quote(v)}]'},"
        for k, v in sorted(ALIASES.items())
    )
    return f"""{comment(BANNER, "//")}
//
// Each controller front-on in its master's millimetre box, parts in paint order. Ids name the
// control by Xbox position (`A`, `LB`, `Up`), the rear grips by the Deck (`L4`…`R5`).

/** A drawing part. Path data is SVG syntax in the master's units. */
export type PadPart =
\t| {{ k: "body" | "panel" | "line"; d: string }}
\t| {{ k: "button" | "trigger"; id: string; d: string }}
\t| {{ k: "stick"; id: string; cx: number; cy: number; r: number; pad: boolean }}
\t| {{ k: "glyph"; on: string; d: string; w: number }}
\t| {{ k: "mark"; on: string; d: string }}
\t| {{
\t\t\tk: "label";
\t\t\ton: string;
\t\t\tx: number;
\t\t\ty: number;
\t\t\tsize: number;
\t\t\ttext: string;
\t  }};

export interface PadArt {{
\tname: string;
\tw: number;
\th: number;
\tparts: PadPart[];
}}

const ART = {{
{entries}
}} satisfies Record<string, PadArt>;

/** The drawing for each `GamepadPref` name the host reports as a pad's `device`. */
export const PAD_ART: Record<string, PadArt> = {{
\t...ART,
{aliases}
}};
"""


def main() -> None:
    arts = [load(p) for p in sorted(MASTERS.glob("*.svg"))]
    tokens = {a["token"] for a in arts}
    for alias, target in ALIASES.items():
        if target not in tokens:
            sys.exit(f"alias {alias} names {target}, which has no master")
    entries = [(a["token"], a["token"]) for a in arts] + sorted(ALIASES.items())
    write(RUST, rust(arts, entries))
    write(TS, ts(arts))
    if shutil.which("rustfmt"):
        subprocess.run(["rustfmt", "--edition", "2024", str(ROOT / RUST)], check=True)
    biome = ROOT / "web" / "node_modules" / ".bin" / "biome"
    if biome.exists():
        subprocess.run(
            [str(biome), "format", "--write", TS.removeprefix("web/")],
            cwd=ROOT / "web",
            check=True,
            capture_output=True,
        )
    else:
        print("  web/node_modules missing: `bun install` in web/, then re-run to format padArt.ts")


if __name__ == "__main__":
    main()
