#!/usr/bin/env python3
"""Emit the three INLINE launcher-icon registries from the assets/launcher-icons masters.

Three clients each need seven paths of up to 3 kB, and a single mangled character is a silently
wrong logo, so these files are generated outright, with their commentary baked in below:

    web/src/components/launcher-icon.tsx           web console, inline SVG
    clients/android/.../components/LauncherIcons.kt Android, Compose ImageVector via PathParser
    crates/pf-console-ui/src/launcher_icons.rs      in-session console UI, Skia Path::from_svg

The baked derivatives (GTK / Windows / Apple) come from gen-launcher-icons.sh, which calls this.

Usage: python3 scripts/gen_launcher_icon_tables.py     (from anywhere; paths are repo-relative)
"""

from __future__ import annotations

from svg_marks import ROOT, comment, mark, write

MASTERS = ROOT / "assets" / "launcher-icons"

# Registry order — the order a reader of any of the three files sees. Live tiles first, then the
# marks that ship dormant (see the masters' README), so "what actually renders today" reads off
# the top of the list.
TOKENS = ["steam", "lutris", "heroic", "playnite", "epic", "gog", "xbox", "hydra"]

BANNER = (
    "GENERATED by scripts/gen_launcher_icon_tables.py from the assets/launcher-icons masters.\n"
    "Do not edit by hand — re-run `bash scripts/gen-launcher-icons.sh` instead.\n"
    "Per-mark provenance and licensing: assets/launcher-icons/README.md."
)

MARKS = [mark(MASTERS, t) for t in TOKENS]


# --- web console -----------------------------------------------------------------------------

rows = "\n".join(
    f'\t{t}: {{\n\t\tviewBox: "0 0 {w:g} {h:g}",\n\t\td: "{d}",\n\t}},'
    for t, d, w, h in MARKS
)
write(
    "web/src/components/launcher-icon.tsx",
    f"""{comment(BANNER, "//")}
//
// The mark a `role: "launcher"` tile draws, resolved from the entry's `icon` token. lucide
// deliberately ships no brand marks, so this is a curated registry — the same shape as
// os-icon.tsx, which does the equivalent job for the host cards' OS marks.
import type {{ FC }} from "react";

/** One monochrome brand mark: original per-icon viewBox, drawn in currentColor. */
export const LAUNCHER_ICONS: Record<string, {{ viewBox: string; d: string }}> = {{
{rows}
}};

/**
 * The mark for an entry's `icon` token, or null — render nothing — when the entry carries no
 * token or names one this console ships no art for. Callers fall back to the title, which is
 * what every launcher tile looked like before the token existed.
 *
 * The token is looked up in the shipped set, never interpolated into anything, so a host
 * sending something unexpected can only ever produce "no icon".
 */
export const LauncherIcon: FC<{{
\ticon?: string | null;
\tclassName?: string;
\tlabel?: string;
}}> = ({{ icon, className, label }}) => {{
\tconst m = icon ? LAUNCHER_ICONS[icon] : undefined;
\tif (!m) return null;
\treturn (
\t\t<svg
\t\t\txmlns="http://www.w3.org/2000/svg"
\t\t\tviewBox={{m.viewBox}}
\t\t\tfill="currentColor"
\t\t\tclassName={{className}}
\t\t\trole={{label ? "img" : undefined}}
\t\t\taria-label={{label}}
\t\t\taria-hidden={{label ? undefined : true}}
\t\t>
\t\t\t{{label && <title>{{label}}</title>}}
\t\t\t<path d={{m.d}} />
\t\t</svg>
\t);
}};

export default LauncherIcon;
""",
)

# --- Android ---------------------------------------------------------------------------------

rows = "\n".join(
    f'    "{t}" to Glyph(\n'
    f"        viewportWidth = {w:g}f,\n"
    f"        viewportHeight = {h:g}f,\n"
    f'        d = "{d}",\n'
    f"    ),"
    for t, d, w, h in MARKS
)
write(
    "clients/android/app/src/main/kotlin/io/unom/punktfunk/components/LauncherIcons.kt",
    f"""package io.unom.punktfunk.components

{comment(BANNER, "//")}

import androidx.compose.ui.graphics.vector.ImageVector

/**
 * The brand mark a `role: "launcher"` tile draws, resolved from the entry's `icon` token — the
 * sibling of [resolveOsIcon], which does the equivalent job for the host cards. Viewports are
 * the masters' own and are NOT all square; [GlyphCache] keeps each mark's ratio.
 */
private val GLYPHS: Map<String, Glyph> = mapOf(
{rows}
)

private val CACHE = GlyphCache("launcher", GLYPHS)

/**
 * The [ImageVector] for an `icon` token, or null when the entry carries none or names a mark
 * this build ships no art for — the caller then falls back to naming the launcher, which is
 * what every launcher tile looked like before the token existed.
 *
 * Tinted by the caller via `tint`, so one mark serves every palette.
 */
fun launcherIcon(token: String?): ImageVector? = CACHE[token ?: return null]
""",
)

# --- in-session console UI (Skia) --------------------------------------------------------------

rows = "\n".join(
    f'    ("{t}", {w:g}.0, {h:g}.0, "{d}"),' for t, d, w, h in MARKS
)
write(
    "crates/pf-console-ui/src/launcher_icons.rs",
    f"""{comment(BANNER, "//!")}
//!
//! Brand mark a `role: "launcher"` tile draws, resolved from the entry's
//! `icon` token.

use crate::icons::MarkTable;
use skia_safe::{{Path, Rect}};

static TABLE: MarkTable = MarkTable::new(&[
{rows}
]);

/// `token`'s mark fitted into `dst`; `None` when this build ships no art for it.
pub fn launcher_mark(token: &str, dst: Rect) -> Option<Path> {{
    TABLE.fit(token, dst)
}}

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn every_glyph_parses() {{
        assert_eq!(TABLE.unparsed(), Vec::<&str>::new());
    }}

    #[test]
    fn unknown_token_draws_nothing() {{
        assert!(launcher_mark("not-a-launcher", Rect::from_wh(64.0, 64.0)).is_none());
    }}
}}
""",
)
