#!/usr/bin/env python3
"""Emit the inline OS-mark registries from the assets/os-icons masters.

    crates/client/pf-console-ui/src/os_marks.rs                in-session console UI, Skia Path::from_svg
    web/src/components/os-icon.tsx                      web console, inline SVG
    clients/decky/src/os-icon.tsx                       Decky plugin, inline SVG
    clients/android/.../components/OsIcons.kt           Android, Compose ImageVector via PathParser

These clients draw path data rather than a baked raster or PDF, so they get the path strings
themselves, generated for the same reason the launcher-icon tables are: a dozen-odd paths of up
to 3.5 kB each, where one mangled character is a silently wrong logo that no test would catch.

Always emits EVERY master, whatever tokens gen-os-icons.sh was invoked with — each output is one
file, and a partial rewrite would drop the rest.

Usage: python3 scripts/gen_os_mark_table.py     (from anywhere; paths are repo-relative)
"""

from __future__ import annotations

import shutil
import subprocess

from svg_marks import ROOT, comment, mark, write

MASTERS = ROOT / "assets" / "os-icons"

BANNER = (
    "GENERATED by scripts/gen_os_mark_table.py from the assets/os-icons masters.\n"
    "Do not edit by hand — re-run `bash scripts/gen-os-icons.sh` instead.\n"
    "Per-mark provenance and licensing: assets/os-icons/README.md."
)


# Sorted so the emitted file has a stable order across runs and machines.
TOKENS = sorted(p.stem for p in MASTERS.glob("*.svg"))
MARKS = [mark(MASTERS, t) for t in TOKENS]

# `!r` on a float always writes a decimal point (`384.0`, never `384`), which matters: the
# table's type is `f32` and a bare integer literal is a type error, not a coercion.
rows = "\n".join(f'    ("{t}", {w!r}, {h!r}, "{d}"),' for t, d, w, h in MARKS)
banner = comment(BANNER, "//!")

body = f"""{banner}
//!
//! Host-tile OS marks, fitted into a destination rect.
//!
//! Tokens come from [`pf_client_core::os::os_icon_tokens`] (most-specific-first,
//! brand aliases included). This module only maps those tokens to path art and
//! letterboxes them. `None` means no art — the tile keeps its monogram.

use crate::icons::MarkTable;
use skia_safe::{{Path, Rect}};

static TABLE: MarkTable = MarkTable::new(&[
{rows}
]);

/// Fitted mark for an OS-identity `chain`, aspect preserved. `None` when no token has art;
/// the tile then draws its monogram. Partial chains still resolve because the shared
/// resolver walks most-specific-first.
pub fn os_mark(chain: &str, dst: Rect) -> Option<Path> {{
    pf_client_core::os::os_icon_tokens(chain)
        .into_iter()
        .find_map(|token| TABLE.fit(&token, dst))
}}

#[cfg(test)]
mod tests {{
    use super::*;

    /// A master that fails to parse is a tile that silently loses its icon.
    #[test]
    fn every_glyph_parses() {{
        assert_eq!(TABLE.unparsed(), Vec::<&str>::new());
    }}

    /// Most-specific-first through the shared resolver; `steamos` → Steam is the alias, not table order.
    #[test]
    fn chains_resolve_most_specific_first() {{
        let dst = Rect::from_wh(64.0, 64.0);
        for chain in [
            "windows",
            "linux",
            "linux/arch/steamos",
            "linux/fedora/bazzite",
            "macos",
        ] {{
            assert!(os_mark(chain, dst).is_some(), "{{chain}} resolved nothing");
        }}
        let known = os_mark("linux/debian/raspbian", dst);
        assert!(
            known.is_some(),
            "an unknown leaf must fall back to its family"
        );
    }}

    #[test]
    fn unknown_chain_draws_nothing() {{
        let dst = Rect::from_wh(64.0, 64.0);
        assert!(os_mark("", dst).is_none());
        assert!(os_mark("plan9/glenda", dst).is_none());
        assert!(os_mark("!!!/???", dst).is_none());
    }}
}}
"""

path = write("crates/client/pf-console-ui/src/os_marks.rs", body)

# CI fmt-gates the whole tree, so a generator that emits anything rustfmt would rewrite leaves
# every regeneration one dirty file away from a blocked commit. Formatting the output here is
# what keeps this template from having to stay hand-wrapped to rustfmt's taste.
if shutil.which("rustfmt"):
    subprocess.run(["rustfmt", "--edition", "2024", str(path)], check=True)

# --- web console -----------------------------------------------------------------------------

rows = "\n".join(
    f'\t{t}: {{\n\t\tviewBox: "0 0 {w:g} {h:g}",\n\t\td: "{d}",\n\t}},'
    for t, d, w, h in MARKS
)
write(
    "web/src/components/os-icon.tsx",
    f"""{comment(BANNER, "//")}
//
// Host OS icon: lucide deliberately ships no brand marks, so this follows the curated-registry
// pattern of api/plugins.ts — a fixed token set, resolved by walking the host's OS-identity
// chain. Distro leaves such as bazzite get their own mark rather than their family's: "a Bazzite
// box" and "a Fedora box" are different machines to the person reading the card.
import {{ Monitor }} from "lucide-react";
import type {{ FC }} from "react";

/** One monochrome brand mark: original per-icon viewBox, drawn in currentColor. */
const OS_ICONS: Record<string, {{ viewBox: string; d: string }}> = {{
{rows}
}};

/** `macos` renders the apple mark, `steamos` the steam mark — same aliases as every client. */
const ALIASES: Record<string, string> = {{ macos: "apple", steamos: "steam" }};

/**
 * Resolve an OS-identity chain (`HostInfo.os`, e.g. "linux/fedora/bazzite") to its mark:
 * walk most-specific-first and take the first token with art, so an unknown distro degrades
 * to its family's mark and finally to Tux. Mirrors pf-client-core's `os_icon_tokens`.
 */
const resolve = (os?: string): {{ viewBox: string; d: string }} | undefined => {{
\tfor (const raw of (os ?? "").toLowerCase().split("/").reverse()) {{
\t\tconst icon = OS_ICONS[ALIASES[raw] ?? raw];
\t\tif (icon) return icon;
\t}}
\treturn undefined;
}};

/** The host's OS mark; a generic monitor when the chain is absent or entirely unknown. */
export const OsIcon: FC<{{
\tos?: string;
\tclassName?: string;
\tlabel?: string;
}}> = ({{ os, className, label }}) => {{
\tconst icon = resolve(os);
\tif (!icon) return <Monitor className={{className}} aria-hidden />;
\treturn (
\t\t<svg
\t\t\txmlns="http://www.w3.org/2000/svg"
\t\t\tviewBox={{icon.viewBox}}
\t\t\tfill="currentColor"
\t\t\tclassName={{className}}
\t\t\trole={{label ? "img" : undefined}}
\t\t\taria-label={{label}}
\t\t\taria-hidden={{label ? undefined : true}}
\t\t>
\t\t\t{{label && <title>{{label}}</title>}}
\t\t\t<path d={{icon.d}} />
\t\t</svg>
\t);
}};

export default OsIcon;
""",
)

# --- Decky plugin ----------------------------------------------------------------------------

rows = "\n".join(
    f'  {t}: {{\n    viewBox: "0 0 {w:g} {h:g}",\n    d: "{d}",\n  }},' for t, d, w, h in MARKS
)
write(
    "clients/decky/src/os-icon.tsx",
    f"""{comment(BANNER, "//")}
//
// The host row's OS mark, resolved from the host's OS-identity chain (mDNS `os` TXT /
// `--list-hosts` `os`, e.g. "linux/fedora/bazzite"): walk the chain most-specific-first and
// take the first token we ship a mark for, so an unknown distro degrades to its family's
// mark and finally to Tux. Mirrors pf-client-core's `os_icon_tokens` (aliases macos→apple,
// steamos→steam); null when the chain is absent or entirely unknown — the row then renders
// exactly as it did before the field existed.
//
// The masters stand in for react-icons: that package's Font Awesome 5 brand set still carries
// the perspective-skewed Windows flag, and it has no Bazzite or CachyOS mark at all.
import {{ FC }} from "react";

/** One monochrome brand mark: original per-icon viewBox, drawn in currentColor. */
const OS_ICONS: Record<string, {{ viewBox: string; d: string }}> = {{
{rows}
}};

/** `macos` renders the apple mark, `steamos` the steam mark — same aliases as every client. */
const ALIASES: Record<string, string> = {{ macos: "apple", steamos: "steam" }};

export function resolveOsIcon(
  os: string | undefined,
): {{ viewBox: string; d: string }} | null {{
  for (const raw of (os ?? "").toLowerCase().split("/").reverse()) {{
    const icon = OS_ICONS[ALIASES[raw] ?? raw];
    if (icon) {{
      return icon;
    }}
  }}
  return null;
}}

/** The mark itself, or nothing — sized/colored by the surrounding text like the lock glyph. */
export const OsMark: FC<{{ os?: string }}> = ({{ os }}) => {{
  const icon = resolveOsIcon(os);
  if (!icon) return null;
  // 1em square with the viewBox letterboxed inside it: the same box react-icons drew, so a
  // non-square mark keeps its aspect ratio instead of being stretched to fill.
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={{icon.viewBox}}
      height="1em"
      width="1em"
      fill="currentColor"
      aria-hidden
    >
      <path d={{icon.d}} />
    </svg>
  );
}};
""",
)

# --- Android ---------------------------------------------------------------------------------

rows = "\n".join(
    f'    "{t}" to Glyph(\n'
    f"        viewportWidth = {w:g}f,\n"
    f"        viewportHeight = {h:g}f,\n"
    f'        d = "{d}",\n'
    f"    ),"
    for t, d, w, h in MARKS
)
write(
    "clients/android/app/src/main/kotlin/io/unom/punktfunk/components/OsIcons.kt",
    f"""package io.unom.punktfunk.components

{comment(BANNER, "//")}

import androidx.compose.ui.graphics.vector.ImageVector
import io.unom.punktfunk.kit.discovery.osIconTokens

/**
 * The host card's OS marks, resolved from the host's OS-identity chain (mDNS `os` TXT,
 * e.g. "linux/fedora/bazzite"): [resolveOsIcon] walks the chain most-specific-first
 * (kit's [osIconTokens] — the shared order + brand aliases) and returns the first mark we
 * ship, so an unknown distro degrades to its family's mark and finally to Tux; null means
 * "no icon", rendering the card exactly as before the field existed.
 *
 * Raw SVG path strings from the masters, one line each; [GlyphCache] builds each once.
 */
private val GLYPHS: Map<String, Glyph> = mapOf(
{rows}
)

private val CACHE = GlyphCache("OsIcon", GLYPHS)

/** The mark for a chain, or null (no icon). Vectors build lazily and cache per token. */
fun resolveOsIcon(chain: String): ImageVector? = osIconTokens(chain).firstNotNullOfOrNull {{ CACHE[it] }}
""",
)
