/* punktfunk console C ABI — see clients/apple/native/src/console.rs */

#ifndef PUNKTFUNK_CONSOLE_H
#define PUNKTFUNK_CONSOLE_H

#pragma once

/* Generated by cbindgen from punktfunk-client-apple. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// `[HostRow]` — the home carousel.
#define PUNKTFUNK_CONSOLE_PUSH_HOSTS 0

// `"Idle"`, `"Busy"`, `{"Failed": "why"}` or `{"Paired": {"key": "…"}}`.
#define PUNKTFUNK_CONSOLE_PUSH_PAIR 1

// `WakeStatus`, or `null` to clear.
#define PUNKTFUNK_CONSOLE_PUSH_WAKE 2

// A JSON string: a one-shot toast.
#define PUNKTFUNK_CONSOLE_PUSH_NOTICE 3

// `{"key": "…", "phase": SpeedPhase}` — the speed test on that host moved on.
#define PUNKTFUNK_CONSOLE_PUSH_SPEED 4

// Any JSON: a library fetch is starting for the shelf on screen.
#define PUNKTFUNK_CONSOLE_PUSH_LIBRARY_BEGIN 5

// `"Loading"`, `"Empty"`, `"Ready"` or `{"Error": {"title", "body", "can_retry"}}`.
#define PUNKTFUNK_CONSOLE_PUSH_LIBRARY_PHASE 6

// `[LibraryGame]` — the fetched catalog.
#define PUNKTFUNK_CONSOLE_PUSH_LIBRARY_GAMES 7

// `[LibraryGame]` — the cached catalog, shown while the fetch runs.
#define PUNKTFUNK_CONSOLE_PUSH_LIBRARY_CACHED 8

// `[{"app_id": "steam:570", "state": "running"}]` — the host's running games.
#define PUNKTFUNK_CONSOLE_PUSH_LIBRARY_RUNNING 9

// `0` fresh, `1` waking, `2` offline.
#define PUNKTFUNK_CONSOLE_PUSH_LIBRARY_STALE 10

// `Settings` changed elsewhere; the shell reads it on its next mutation. Not a save.
#define PUNKTFUNK_CONSOLE_PUSH_SETTINGS 11

// `[{id, name, overrides}]` — the preset catalog.
#define PUNKTFUNK_CONSOLE_PUSH_PRESETS 12

// `KnownHosts` — the records `punktfunk://` links are built from.
#define PUNKTFUNK_CONSOLE_PUSH_KNOWN_HOSTS 13

// `{"label", "pref", "pads": [PadInfo]}` — the connected controllers.
#define PUNKTFUNK_CONSOLE_PUSH_PADS 14

// `{}` for Home, `{"library": HostRow}` for a shelf — re-roots on the next frame.
#define PUNKTFUNK_CONSOLE_PUSH_NAVIGATE 15

// `{"id", "title", "message", "choices": [..]}` — a question over the top screen; the
// answer comes back as the `PromptAnswer` command.
#define PUNKTFUNK_CONSOLE_PUSH_PROMPT 16

// `[{"heading", "text"}]` — what this app bundles, for the Licences screen. The answer to
// the `LoadLicenses` command.
#define PUNKTFUNK_CONSOLE_PUSH_LICENSES 17

// `{"held": [..], "axes": [[name, v]]}` — the pad's reading while the `PadTest` command is on.
#define PUNKTFUNK_CONSOLE_PUSH_PAD_TEST 18

// One console. Opaque to C.
typedef struct PunktfunkConsole PunktfunkConsole;

// Safe-area insets in texture pixels.
typedef struct {
    float left;
    float top;
    float right;
    float bottom;
} PunktfunkInsets;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Build a console over Swift's Metal device and queue. `options_json` is the bridge's
// `CreateOptions`. NULL if the JSON or Skia's Metal context fails; the log says which.
//
// # Safety
// `options_json` is a NUL-terminated string. `mtl_device` and `mtl_queue` are a live
// `id<MTLDevice>` and an `id<MTLCommandQueue>` on it; the console retains both.
PunktfunkConsole *punktfunk_console_new(const char *options_json,
                                        void *mtl_device,
                                        void *mtl_queue);

// Free a console. NULL is a no-op. Off the creating thread it leaks rather than drop the
// shell there.
//
// # Safety
// `c` is NULL or from `punktfunk_console_new`, and is not used again.
void punktfunk_console_free(PunktfunkConsole *c);

// Draw one frame into `mtl_texture` (BGR10A2 or BGRA8, `width`×`height`) and submit it to the queue.
// `scale` is design units per pixel; `0` takes the shell's own formula. `false` = nothing
// drawn (idle, or the texture could not be wrapped): present nothing.
//
// # Safety
// `c` is live. `mtl_texture` is an `id<MTLTexture>` from the console's device, render-target
// usable, BGRA8Unorm, at least `width`×`height`.
bool punktfunk_console_frame(const PunktfunkConsole *c,
                             void *mtl_texture,
                             uint32_t width,
                             uint32_t height,
                             PunktfunkInsets insets,
                             double scale);

// A discrete menu event: 0..3 move up/down/left/right, 4 confirm, 5 back, 6 secondary (Y),
// 7 tertiary (X), 8 jump back (L1), 9 jump forward (R1), 10/11 a remote's OK down/up (acts
// on release, held it is the card's menu). `source` 1 = a pad (its glyphs), 0 = a remote or
// keyboard. `false` = Back at the root: the press is the system's.
//
// # Safety
// `c` is live.
bool punktfunk_console_menu(const PunktfunkConsole *c, uint8_t event, uint8_t source);

// Whether a Back would leave the console rather than pop a screen. A tvOS host binds the
// Menu button only while this is false, so at the root the press reaches the system.
//
// # Safety
// `c` is live.
bool punktfunk_console_at_root(const PunktfunkConsole *c);

// Whether the console's launch hold is up. The app keeps the console over the stream it
// dialled while this is true, and gives the stream the screen once it is false.
//
// # Safety
// `c` is live.
bool punktfunk_console_holds_launch(const PunktfunkConsole *c);

// Touch or mouse in texture pixels: kind 0 move, 1 primary down (a mouse, acts at once),
// 2 primary up, 3 secondary down (= Back), 4 wheel (`dy` steps, + = up), 5 cancel,
// 6 primary down from a finger — deferred, so a swipe scrolls instead. `true` = consumed.
//
// # Safety
// `c` is live.
bool punktfunk_console_pointer(const PunktfunkConsole *c, uint8_t kind, float x, float y, float dy);

// A hardware key: 0..3 left/right/up/down, 4 return, 5 space, 6 escape, 7 backspace,
// 8 page up, 9 page down, 10 tab, 11 Y, 12 X. `true` = consumed.
//
// # Safety
// `c` is live.
bool punktfunk_console_key(const PunktfunkConsole *c, uint8_t key, bool shift, bool repeat);

// Typed text while the console reports `editing`.
//
// # Safety
// `c` is live; `utf8` is a NUL-terminated string.
void punktfunk_console_text(const PunktfunkConsole *c, const char *utf8);

// Where the session the console asked for stands: 0 connecting, 1 streaming, 2 failed,
// 3 ended (`message` NULL or empty = clean), 4 reconnecting.
//
// # Safety
// `c` is live; `message` is NULL or a NUL-terminated string.
void punktfunk_console_phase(const PunktfunkConsole *c, uint8_t phase, const char *message);

// Hand the console a model update; `kind` is a `PUNKTFUNK_CONSOLE_PUSH_*`. A bad kind or bad
// JSON is a logged no-op.
//
// # Safety
// `c` is live; `json_text` is a NUL-terminated string.
void punktfunk_console_push(const PunktfunkConsole *c, uint8_t kind, const char *json_text);

// One title's poster, encoded (JPEG/PNG); the shell decodes it at the size it draws.
//
// # Safety
// `c` is live; `id` is a NUL-terminated string; `bytes` is `len` readable bytes.
void punktfunk_console_art(const PunktfunkConsole *c,
                           const char *id,
                           const uint8_t *bytes,
                           uintptr_t len);

// The next event the shell raised, or NULL when there is none: `{"action": OverlayAction}`,
// `{"pulse": "move"|"confirm"|"boundary"}`, `{"editing": bool}`, `{"announce": "…"}` or
// `{"settings": Settings}` (persist it). Free with `punktfunk_console_string_free`.
//
// # Safety
// `c` is live.
char *punktfunk_console_next_event(const PunktfunkConsole *c);

// Every `ConsoleCmd` queued since the last call, as a JSON array (`[]` when none). Free with
// `punktfunk_console_string_free`.
//
// # Safety
// `c` is live.
char *punktfunk_console_drain_cmds(const PunktfunkConsole *c);

// The console's background palettes in cycle order, as `[{"id", "name"}]`: what a native
// picker offers for `ui_palette`. Free with `punktfunk_console_string_free`.
char *punktfunk_console_palettes(void);

// Free a string from `punktfunk_console_next_event`, `punktfunk_console_drain_cmds` or
// `punktfunk_console_palettes`.
//
// # Safety
// `s` is NULL or one of those strings, freed once.
void punktfunk_console_string_free(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PUNKTFUNK_CONSOLE_H */
