//! The About dialog: the app's licence and the third-party notices.

use adw::prelude::*;

/// punktfunk's own license (MIT OR Apache-2.0), shown on the About dialog's Legal page.
const APP_LICENSE: &str = concat!(
    "Punktfunk is licensed under MIT OR Apache-2.0, at your option.\n\n",
    "================================ MIT ================================\n\n",
    include_str!("../../../../LICENSE-MIT"),
    "\n\n=============================== Apache-2.0 ===============================\n\n",
    include_str!("../../../../LICENSE-APACHE"),
);
/// Third-party software notices for the Rust crates THIS CLIENT links — the shell, the
/// session streamer, the headless CLI and the update helper (generated by
/// scripts/gen-third-party-notices.sh; shown as a Legal section in the About dialog, and
/// shipped as /usr/share/doc/punktfunk-client/THIRD-PARTY-NOTICES.txt by the packages).
///
/// Deliberately the client-scoped file and not the workspace-wide one at the repo root: the
/// root file covers the whole workspace, so it attributes crates this app never links, and
/// the section below it claims exactly what is here.
const THIRD_PARTY_NOTICES: &str = include_str!("../../THIRD-PARTY-NOTICES.txt");

/// The dynamically linked system libraries — not in the crate notices, since they aren't
/// crates. Their full texts ship with each project rather than being vendored here.
const SYSTEM_LIBRARY_NOTICES: &str =
    "This application dynamically links system libraries under their own licenses, including \
     GTK 4 and libadwaita (LGPL v2.1+), PipeWire (MIT), and SDL 3 (Zlib). \
     Their full license texts are available from each project. Video decoding uses the \
     system's own Vulkan Video and VAAPI drivers (loaded at runtime, never linked), with \
     OpenH264 and rav1d — both BSD-2-Clause, and both in the Rust crate notices — as the \
     CPU fallback; no FFmpeg is linked or bundled.";

/// Show the About dialog (app license + the third-party-software Legal section) — reached
/// from the primary menu (app.rs `win.about`).
pub fn show_about(parent: &impl IsA<gtk::Widget>) {
    // Every licence field here is PANGO MARKUP, not plain text — so a crate author's
    // `<name@example.com>` reads as an unclosed tag and Pango drops the whole section with
    // "is not a valid name: @". The notices are generated from crate metadata and are full of
    // those, so they are escaped rather than trusted. Nothing in them wants markup anyway.
    let license = gtk::glib::markup_escape_text(APP_LICENSE);
    let crate_notices = gtk::glib::markup_escape_text(THIRD_PARTY_NOTICES);
    let system_notices = gtk::glib::markup_escape_text(SYSTEM_LIBRARY_NOTICES);
    let about = adw::AboutDialog::builder()
        .application_name("Punktfunk")
        // The app's own icon, by the id the desktop entry and the icon theme both use. It
        // resolves from the installed hicolor icon; an uninstalled dev run simply shows the
        // generic fallback rather than nothing.
        .application_icon(crate::app::APP_ID)
        .developer_name("unom")
        // The package version `--version` prints, canary suffix included (build.rs).
        .version(env!("PUNKTFUNK_VERSION"))
        .website("https://git.unom.io/unom/punktfunk")
        .license_type(gtk::License::Custom)
        .license(license.as_str())
        .build();
    // The native (GTK/PipeWire/SDL3) components are dynamically linked under their own
    // (LGPL/Zlib/MIT) licenses; the Rust crate notices are the substantive attribution set.
    about.add_legal_section(
        "Third-party software (Rust crates)",
        None,
        gtk::License::Custom,
        Some(crate_notices.as_str()),
    );
    about.add_legal_section(
        "Third-party software (system libraries)",
        None,
        gtk::License::Custom,
        Some(system_notices.as_str()),
    );
    about.present(Some(parent));
}
